package sumaregi

// GetTransactionsOpts represents options for GetTransactions.
type GetTransactionsOpts struct {
	Fields                      []string `url:"fields,omitempty"`
	Sort                        string   `url:"sort,omitempty"`
	Limit                       int      `url:"limit,omitempty"`
	Page                        int      `url:"page,omitempty"`
	TransactionHeadIDFrom       string   `url:"transaction_head_id-from,omitempty"`
	TransactionHeadIDTo         string   `url:"transaction_head_id-to,omitempty"`
	TransactionDateTimeFrom     string   `url:"transaction_date_time-from,omitempty"`
	TransactionDateTimeTo       string   `url:"transaction_date_time-to,omitempty"`
	TransactionHeadDivision     string   `url:"transaction_head_division,omitempty"`
	StoreID                     int      `url:"store_id,omitempty"`
	TerminalTranDateTimeFrom    string   `url:"terminal_tran_date_time-from,omitempty"`
	TerminalTranDateTimeTo      string   `url:"terminal_tran_date_time-to,omitempty"`
	AdjustmentDateTime          string   `url:"adjustment_date_time,omitempty"`
	SumDate                     string   `url:"sum_date,omitempty"`
	SumDateFrom                 string   `url:"sum_date-from,omitempty"`
	SumDateTo                   string   `url:"sum_date-to,omitempty"`
	CustomerCode                string   `url:"customer_code,omitempty"`
	TransactionUUID             string   `url:"transaction_uuid,omitempty"`
	Barcode                     string   `url:"barcode,omitempty"`
	UpdDateTimeFrom             string   `url:"upd_date_time-from,omitempty"`
	UpdDateTimeTo               string   `url:"upd_date_time-to,omitempty"`
	WithDetails                 string   `url:"with_details,omitempty"`
	WithDepositOthers           string   `url:"with_deposit_others,omitempty"`
	WithLayaway                 string   `url:"with_layaway,omitempty"`
	WithLayaways                string   `url:"with_layaways,omitempty"`
	WithLayawayPickUp           string   `url:"with_layaway_pick_up,omitempty"`
	WithLayawayPickUps          string   `url:"with_layaway_pick_ups,omitempty"`
	WithMoneyControl            string   `url:"with_money_control,omitempty"`
	WithDetailProductAttributes string   `url:"with_detail_product_attributes,omitempty"`
}

// GetTransactionsResponse represents a response from GetTransactions.
type GetTransactionsResponse []struct {
	TransactionHeadID              string `json:"transactionHeadId"`
	TransactionDateTime            string `json:"transactionDateTime"`
	TransactionHeadDivision        string `json:"transactionHeadDivision"`
	CancelDivision                 string `json:"cancelDivision"`
	UnitNonDiscountsubtotal        string `json:"unitNonDiscountsubtotal"`
	UnitDiscountsubtotal           string `json:"unitDiscountsubtotal"`
	UnitStaffDiscountsubtotal      string `json:"unitStaffDiscountsubtotal"`
	UnitBargainDiscountsubtotal    string `json:"unitBargainDiscountsubtotal"`
	Subtotal                       string `json:"subtotal"`
	SubtotalForDiscount            string `json:"subtotalForDiscount"`
	SubtotalDiscountPrice          string `json:"subtotalDiscountPrice"`
	SubtotalDiscountRate           string `json:"subtotalDiscountRate"`
	SubtotalDiscountDivision       string `json:"subtotalDiscountDivision"`
	PointDiscount                  string `json:"pointDiscount"`
	CouponDiscount                 string `json:"couponDiscount"`
	Total                          string `json:"total"`
	TaxInclude                     string `json:"taxInclude"`
	TaxExclude                     string `json:"taxExclude"`
	RoundingDivision               string `json:"roundingDivision"`
	RoundingPrice                  string `json:"roundingPrice"`
	CashTotal                      string `json:"cashTotal"`
	CreditTotal                    string `json:"creditTotal"`
	Deposit                        string `json:"deposit"`
	DepositCash                    string `json:"depositCash"`
	DepositCredit                  string `json:"depositCredit"`
	Change                         string `json:"change"`
	TipCash                        string `json:"tipCash"`
	TipCredit                      string `json:"tipCredit"`
	Amount                         string `json:"amount"`
	ReturnAmount                   string `json:"returnAmount"`
	CostTotal                      string `json:"costTotal"`
	SalesHeadDivision              string `json:"salesHeadDivision"`
	InTaxSalesTotal                string `json:"inTaxSalesTotal"`
	OutTaxSalesTotal               string `json:"outTaxSalesTotal"`
	NonTaxSalesTotal               string `json:"nonTaxSalesTotal"`
	NonSalesTargetTotal            string `json:"nonSalesTargetTotal"`
	NonSalesTargetOutTaxTotal      string `json:"nonSalesTargetOutTaxTotal"`
	NonSalesTargetInTaxTotal       string `json:"nonSalesTargetInTaxTotal"`
	NonSalesTargetTaxFreeTotal     string `json:"nonSalesTargetTaxFreeTotal"`
	NonSalesTargetCostTotal        string `json:"nonSalesTargetCostTotal"`
	NonSalesTargetAmount           string `json:"nonSalesTargetAmount"`
	NonSalesTargetReturnAmount     string `json:"nonSalesTargetReturnAmount"`
	NewPoint                       string `json:"newPoint"`
	SpendPoint                     string `json:"spendPoint"`
	Point                          string `json:"point"`
	TotalPoint                     string `json:"totalPoint"`
	CurrentMile                    string `json:"currentMile"`
	EarnMile                       string `json:"earnMile"`
	TotalMile                      string `json:"totalMile"`
	AdjustmentMile                 string `json:"adjustmentMile"`
	AdjustmentMileDivision         string `json:"adjustmentMileDivision"`
	AdjustmentMileValue            string `json:"adjustmentMileValue"`
	StoreID                        string `json:"storeId"`
	StoreCode                      string `json:"storeCode"`
	TerminalID                     string `json:"terminalId"`
	CustomerID                     string `json:"customerId"`
	CustomerCode                   string `json:"customerCode"`
	TerminalTranID                 string `json:"terminalTranId"`
	TerminalTranDateTime           string `json:"terminalTranDateTime"`
	SumDivision                    string `json:"sumDivision"`
	AdjustmentDateTime             string `json:"adjustmentDateTime"`
	SumDate                        string `json:"sumDate"`
	CustomerRank                   string `json:"customerRank"`
	CustomerGroupID                string `json:"customerGroupId"`
	CustomerGroupID2               string `json:"customerGroupId2"`
	CustomerGroupID3               string `json:"customerGroupId3"`
	CustomerGroupID4               string `json:"customerGroupId4"`
	CustomerGroupID5               string `json:"customerGroupId5"`
	StaffID                        string `json:"staffId"`
	StaffCode                      string `json:"staffCode"`
	StaffName                      string `json:"staffName"`
	CreditDivision                 string `json:"creditDivision"`
	PaymentCount                   string `json:"paymentCount"`
	SlipNumber                     string `json:"slipNumber"`
	CancelSlipNumber               string `json:"cancelSlipNumber"`
	AuthNumber                     string `json:"authNumber"`
	AuthDate                       string `json:"authDate"`
	CardCompany                    string `json:"cardCompany"`
	Denomination                   string `json:"denomination"`
	Memo                           string `json:"memo"`
	ReceiptMemo                    string `json:"receiptMemo"`
	Carriage                       string `json:"carriage"`
	Commission                     string `json:"commission"`
	GuestNumbers                   string `json:"guestNumbers"`
	GuestNumbersMale               string `json:"guestNumbersMale"`
	GuestNumbersFemale             string `json:"guestNumbersFemale"`
	GuestNumbersUnknown            string `json:"guestNumbersUnknown"`
	EnterDateTime                  string `json:"enterDateTime"`
	TaxFreeSalesDivision           string `json:"taxFreeSalesDivision"`
	NetTaxFreeGeneralTaxInclude    string `json:"netTaxFreeGeneralTaxInclude"`
	NetTaxFreeGeneralTaxExclude    string `json:"netTaxFreeGeneralTaxExclude"`
	NetTaxFreeConsumableTaxInclude string `json:"netTaxFreeConsumableTaxInclude"`
	NetTaxFreeConsumableTaxExclude string `json:"netTaxFreeConsumableTaxExclude"`
	Tags                           string `json:"tags"`
	PointGivingDivision            string `json:"pointGivingDivision"`
	PointGivingUnitPrice           string `json:"pointGivingUnitPrice"`
	PointGivingUnit                string `json:"pointGivingUnit"`
	PointSpendDivision             string `json:"pointSpendDivision"`
	MileageDivision                string `json:"mileageDivision"`
	MileageLabel                   string `json:"mileageLabel"`
	CustomerPinCode                string `json:"customerPinCode"`
	ReturnSales                    string `json:"returnSales"`
	DisposeDivision                string `json:"disposeDivision"`
	DisposeServerTransactionHeadID string `json:"disposeServerTransactionHeadId"`
	CancelDateTime                 string `json:"cancelDateTime"`
	SellDivision                   string `json:"sellDivision"`
	TaxRate                        string `json:"taxRate"`
	TaxRounding                    string `json:"taxRounding"`
	DiscountRoundingDivision       string `json:"discountRoundingDivision"`
	TransactionUUID                string `json:"transactionUuid"`
	ExchangeTicketNo               string `json:"exchangeTicketNo"`
	GiftReceiptValidDays           string `json:"giftReceiptValidDays"`
	Barcode                        string `json:"barcode"`
	UpdDateTime                    string `json:"updDateTime"`
	Details                        []struct {
		TransactionHeadID            string `json:"transactionHeadId"`
		TransactionDetailID          string `json:"transactionDetailId"`
		ParentTransactionDetailID    string `json:"parentTransactionDetailId"`
		TransactionDetailDivision    string `json:"transactionDetailDivision"`
		ProductID                    string `json:"productId"`
		ProductCode                  string `json:"productCode"`
		ProductName                  string `json:"productName"`
		PrintReceiptProductName      string `json:"printReceiptProductName"`
		Color                        string `json:"color"`
		Size                         string `json:"size"`
		GroupCode                    string `json:"groupCode"`
		TaxDivision                  string `json:"taxDivision"`
		Price                        string `json:"price"`
		SalesPrice                   string `json:"salesPrice"`
		UnitDiscountPrice            string `json:"unitDiscountPrice"`
		UnitDiscountRate             string `json:"unitDiscountRate"`
		UnitDiscountDivision         string `json:"unitDiscountDivision"`
		Cost                         string `json:"cost"`
		Quantity                     string `json:"quantity"`
		UnitNonDiscountSum           string `json:"unitNonDiscountSum"`
		UnitDiscountSum              string `json:"unitDiscountSum"`
		UnitDiscountedSum            string `json:"unitDiscountedSum"`
		CostSum                      string `json:"costSum"`
		CategoryID                   string `json:"categoryId"`
		CategoryName                 string `json:"categoryName"`
		DiscriminationNo             string `json:"discriminationNo"`
		SalesDivision                string `json:"salesDivision"`
		ProductDivision              string `json:"productDivision"`
		InventoryReservationDivision string `json:"inventoryReservationDivision"`
		PointNotApplicable           string `json:"pointNotApplicable"`
		CalcDiscount                 string `json:"calcDiscount"`
		TaxFreeDivision              string `json:"taxFreeDivision"`
		TaxFreeCommodityPrice        string `json:"taxFreeCommodityPrice"`
		TaxFree                      string `json:"taxFree"`
		ProductBundleGroupID         string `json:"productBundleGroupId"`
		DiscountPriceProportional    string `json:"discountPriceProportional"`
		DiscountPointProportional    string `json:"discountPointProportional"`
		DiscountCouponProportional   string `json:"discountCouponProportional"`
		TaxIncludeProportional       string `json:"taxIncludeProportional"`
		TaxExcludeProportional       string `json:"taxExcludeProportional"`
		ProductBundleProportional    string `json:"productBundleProportional"`
		StaffDiscountProportional    string `json:"staffDiscountProportional"`
		BargainDiscountProportional  string `json:"bargainDiscountProportional"`
		RoundingPriceProportional    string `json:"roundingPriceProportional"`
		ProductStaffDiscountRate     string `json:"productStaffDiscountRate"`
		StaffRank                    string `json:"staffRank"`
		StaffRankName                string `json:"staffRankName"`
		StaffDiscountRate            string `json:"staffDiscountRate"`
		StaffDiscountDivision        string `json:"staffDiscountDivision"`
		ApplyStaffDiscountRate       string `json:"applyStaffDiscountRate"`
		ApplyStaffDiscountPrice      string `json:"applyStaffDiscountPrice"`
		BargainID                    string `json:"bargainId"`
		BargainName                  string `json:"bargainName"`
		BargainDivision              string `json:"bargainDivision"`
		BargainValue                 string `json:"bargainValue"`
		ApplyBargainValue            string `json:"applyBargainValue"`
		ApplyBargainDiscountPrice    string `json:"applyBargainDiscountPrice"`
		TaxRate                      string `json:"taxRate"`
		StandardTaxRate              string `json:"standardTaxRate"`
		ModifiedTaxRate              string `json:"modifiedTaxRate"`
		ReduceTaxID                  string `json:"reduceTaxId"`
		ReduceTaxName                string `json:"reduceTaxName"`
		ReduceTaxRate                string `json:"reduceTaxRate"`
		ReduceTaxPrice               string `json:"reduceTaxPrice"`
		ReduceTaxMemberPrice         string `json:"reduceTaxMemberPrice"`
		Memo                         string `json:"memo"`
		ProductAttributes            []struct {
			TransactionHeadID   string `json:"transactionHeadId"`
			TransactionDetailID string `json:"transactionDetailId"`
			Code                string `json:"code"`
			Name                string `json:"name"`
		} `json:"productAttributes"`
		RfidTags []string `json:"rfidTags"`
	} `json:"details"`
	DepositOthers []struct {
		TransactionHeadID     string `json:"transactionHeadId"`
		No                    string `json:"no"`
		PaymentMethodID       string `json:"paymentMethodId"`
		PaymentMethodCode     string `json:"paymentMethodCode"`
		PaymentMethodName     string `json:"paymentMethodName"`
		DepositOthers         string `json:"depositOthers"`
		PaymentUnitPrice      string `json:"paymentUnitPrice"`
		PaymentChangeFlag     int    `json:"paymentChangeFlag"`
		PaymentDivision       string `json:"paymentDivision"`
		PaymentSecuritiesFlag int    `json:"paymentSecuritiesFlag"`
		DenominationCode      string `json:"denominationCode"`
		DenominationName      string `json:"denominationName"`
		CardCompanyName       string `json:"cardCompanyName"`
		SlipNumber            string `json:"slipNumber"`
		CancelSlipNumber      string `json:"cancelSlipNumber"`
		PointGivingUnitPrice  string `json:"pointGivingUnitPrice"`
		PointGivingUnit       string `json:"pointGivingUnit"`
	} `json:"depositOthers"`
	Layaway struct {
		TransactionHeadID       string `json:"transactionHeadId"`
		PickUpDate              string `json:"pickUpDate"`
		Status                  string `json:"status"`
		PartPayment             string `json:"partPayment"`
		PartPaymentClass        string `json:"partPaymentClass"`
		PickUpTransactionHeadID string `json:"pickUpTransactionHeadId"`
		DisabledEdit            string `json:"disabledEdit"`
	} `json:"layaway"`
	Layaways []struct {
		TransactionHeadID       string `json:"transactionHeadId"`
		PickUpDate              string `json:"pickUpDate"`
		Status                  string `json:"status"`
		PartPayment             string `json:"partPayment"`
		PartPaymentClass        string `json:"partPaymentClass"`
		PickUpTransactionHeadID string `json:"pickUpTransactionHeadId"`
		DisabledEdit            string `json:"disabledEdit"`
	} `json:"layaways"`
	LayawayPickUp struct {
		TransactionHeadID              string `json:"transactionHeadId"`
		LayawayServerTransactionHeadID string `json:"layawayServerTransactionHeadId"`
		ReceivedDepositCash            string `json:"receivedDepositCash"`
		ReceivedDepositCredit          string `json:"receivedDepositCredit"`
	} `json:"layawayPickUp"`
	LayawayPickUps []struct {
		TransactionHeadID              string `json:"transactionHeadId"`
		LayawayServerTransactionHeadID string `json:"layawayServerTransactionHeadId"`
		ReceivedDepositCash            string `json:"receivedDepositCash"`
		ReceivedDepositCredit          string `json:"receivedDepositCredit"`
	} `json:"layawayPickUps"`
	MoneyControl struct {
		TransactionHeadID     string `json:"transactionHeadId"`
		AttributeDivision     string `json:"attributeDivision"`
		AttributeDivisionName string `json:"attributeDivisionName"`
	} `json:"moneyControl"`
}

// GetTransactionDetailOpts represents options for GetTransactionDetail.
type GetTransactionDetailOpts struct {
	Fields                      []string `url:"fields,omitempty"`                         // Array of fields (comma-separated)
	Sort                        string   `url:"sort,omitempty"`                           // Sort order (comma-separated)
	Limit                       int      `url:"limit,omitempty"`                          // Maximum number of results
	Page                        int      `url:"page,omitempty"`                           // Page number
	WithDiscounts               string   `url:"with_discounts,omitempty"`                 // Add discount information ("all" or "none")
	WithDetailProductAttributes string   `url:"with_detail_product_attributes,omitempty"` // Add product attribute information ("all" or "none")
}

// GetTransactionDetailResponse represents a response from GetTransactionDetail.
type GetTransactionDetailResponse []struct {
	TransactionHeadID            string `json:"transactionHeadId"`
	TransactionDetailID          string `json:"transactionDetailId"`
	ParentTransactionDetailID    string `json:"parentTransactionDetailId"`
	TransactionDetailDivision    string `json:"transactionDetailDivision"`
	ProductID                    string `json:"productId"`
	ProductCode                  string `json:"productCode"`
	ProductName                  string `json:"productName"`
	PrintReceiptProductName      string `json:"printReceiptProductName"`
	Color                        string `json:"color"`
	Size                         string `json:"size"`
	GroupCode                    string `json:"groupCode"`
	TaxDivision                  string `json:"taxDivision"`
	Price                        string `json:"price"`
	SalesPrice                   string `json:"salesPrice"`
	UnitDiscountPrice            string `json:"unitDiscountPrice"`
	UnitDiscountRate             string `json:"unitDiscountRate"`
	UnitDiscountDivision         string `json:"unitDiscountDivision"`
	Cost                         string `json:"cost"`
	Quantity                     string `json:"quantity"`
	UnitNonDiscountSum           string `json:"unitNonDiscountSum"`
	UnitDiscountSum              string `json:"unitDiscountSum"`
	UnitDiscountedSum            string `json:"unitDiscountedSum"`
	CostSum                      string `json:"costSum"`
	CategoryID                   string `json:"categoryId"`
	CategoryName                 string `json:"categoryName"`
	DiscriminationNo             string `json:"discriminationNo"`
	SalesDivision                string `json:"salesDivision"`
	ProductDivision              string `json:"productDivision"`
	InventoryReservationDivision string `json:"inventoryReservationDivision"`
	PointNotApplicable           string `json:"pointNotApplicable"`
	CalcDiscount                 string `json:"calcDiscount"`
	TaxFreeDivision              string `json:"taxFreeDivision"`
	TaxFreeCommodityPrice        string `json:"taxFreeCommodityPrice"`
	TaxFree                      string `json:"taxFree"`
	ProductBundleGroupID         string `json:"productBundleGroupId"`
	DiscountPriceProportional    string `json:"discountPriceProportional"`
	DiscountPointProportional    string `json:"discountPointProportional"`
	DiscountCouponProportional   string `json:"discountCouponProportional"`
	TaxIncludeProportional       string `json:"taxIncludeProportional"`
	TaxExcludeProportional       string `json:"taxExcludeProportional"`
	ProductBundleProportional    string `json:"productBundleProportional"`
	StaffDiscountProportional    string `json:"staffDiscountProportional"`
	BargainDiscountProportional  string `json:"bargainDiscountProportional"`
	RoundingPriceProportional    string `json:"roundingPriceProportional"`
	ProductStaffDiscountRate     string `json:"productStaffDiscountRate"`
	StaffRank                    string `json:"staffRank"`
	StaffRankName                string `json:"staffRankName"`
	StaffDiscountRate            string `json:"staffDiscountRate"`
	StaffDiscountDivision        string `json:"staffDiscountDivision"`
	ApplyStaffDiscountRate       string `json:"applyStaffDiscountRate"`
	ApplyStaffDiscountPrice      string `json:"applyStaffDiscountPrice"`
	BargainID                    string `json:"bargainId"`
	BargainName                  string `json:"bargainName"`
	BargainDivision              string `json:"bargainDivision"`
	BargainValue                 string `json:"bargainValue"`
	ApplyBargainValue            string `json:"applyBargainValue"`
	ApplyBargainDiscountPrice    string `json:"applyBargainDiscountPrice"`
	TaxRate                      string `json:"taxRate"`
	StandardTaxRate              string `json:"standardTaxRate"`
	ModifiedTaxRate              string `json:"modifiedTaxRate"`
	ReduceTaxID                  string `json:"reduceTaxId"`
	ReduceTaxName                string `json:"reduceTaxName"`
	ReduceTaxRate                string `json:"reduceTaxRate"`
	ReduceTaxPrice               string `json:"reduceTaxPrice"`
	ReduceTaxMemberPrice         string `json:"reduceTaxMemberPrice"`
	Memo                         string `json:"memo"`
	Discounts                    []struct {
		TransactionHeadID           string `json:"transactionHeadId"`
		TransactionDetailID         string `json:"transactionDetailId"`
		TransactionDiscountDivision string `json:"transactionDiscountDivision"`
		DiscountDivision            string `json:"discountDivision"`
		DiscountDivisionName        string `json:"discountDivisionName"`
		AwardType                   string `json:"awardType"`
		AwardValue                  string `json:"awardValue"`
		DiscountPrice               string `json:"discountPrice"`
	} `json:"discounts"`
	ProductAttributes []struct {
		TransactionHeadID   string `json:"transactionHeadId"`
		TransactionDetailID string `json:"transactionDetailId"`
		Code                string `json:"code"`
		Name                string `json:"name"`
	} `json:"productAttributes"`
	RfidTags []string `json:"rfidTags"`
}
